version: "3"
# Author: Haoji Liu
services:
  grpc:
    volumes:
      - ./grpc_server/src:/srv/src
    build: ./grpc_server
    container_name: cmpe275_grpc
    ports:
      - "8080:8080" # for local to make grpc call to container
      - "9004:9004" # supervisord
    tty: true
  db:
    ports:
      - "9003:9003" # supervisord
      - "28017:28017" # mongo http port
    volumes:
      - ./database_node/src:/srv/src
    build: ./database_node
    container_name: cmpe275_db
    tty: true
  task_scheduler:
    ports:
      - "9002:9002" # supervisord
      - "5559:5559" # read client port
      - "5560:5560" # read worker port
      - "80:80" # heartbeat register
    # So that wysiwyg
    volumes:
      - ./task_scheduler/src:/srv/src
    build: ./task_scheduler
    container_name: cmpe275_task_scheduler
    tty: true
